// Generated by scripts/build-brand.mjs. Do not edit by hand.
// Shared geometry for the in-app mark; the standalone SVG and the Lottie loop
// in assets/branding are built from the same numbers.

export const LOGO_BOX = 48;
export const LOGO_CENTRE = 24;
export const LOGO_RING_RADIUS = 16;
export const LOGO_STROKE = 5;
export const LOGO_NODE_RADIUS = 6.5;
export const LOGO_BEAD_RADIUS = 4.3;
export const LOGO_RIPPLE_RADIUS = 21;
export const LOGO_RIPPLE_STROKE = 1.6;
/** Scale the ripple circle (drawn at ring radius) down to the node edge. */
export const LOGO_RIPPLE_FROM = 0.406;
export const LOGO_RIPPLE_TO = 1.313;
export const LOGO_BEAD = { cx: 37.419, cy: 15.286 };
export const LOGO_ARCS = [
  "M39.757 21.222A16 16 0 0 1 27.871 39.525",
  "M21.222 39.757A16 16 0 0 1 11.056 14.595",
  "M16 10.144A16 16 0 0 1 32.947 10.735",
];
